#!/usr/bin/env python3
"""Add a real, navigable tag tree to PDFs generated by ReportLab.

ReportLab 4.x does not emit tagged PDFs through ``pdfgen.canvas``.  This
post-processing step keeps the rendered pages, links, outlines and document
metadata, while adding the structures that assistive technology needs to map
marked page content back to a semantic tree:

* ``/MarkInfo`` with ``/Marked true``;
* ``/StructTreeRoot`` and a document structure element;
* one titled ``/Sect`` structure element per page;
* ``/StructParents`` and a matching ``/ParentTree`` entry for every page;
* marked content with a stable ``/MCID`` in every page content stream.

The structure is intentionally conservative.  It exposes the reading order
already present in each ReportLab content stream without pretending that every
decorative rectangle or individual text fragment has richer semantics than the
generator can prove.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Sequence

from pypdf import PdfReader, PdfWriter
from pypdf.generic import (
    ArrayObject,
    BooleanObject,
    DecodedStreamObject,
    DictionaryObject,
    NameObject,
    NumberObject,
    TextStringObject,
)


def _name(value: str) -> NameObject:
    return NameObject(value if value.startswith("/") else f"/{value}")


def _tag_page_content(writer: PdfWriter, page, tag: str = "Sect", mcid: int = 0) -> None:
    """Wrap the complete page stream in one marked-content sequence."""

    contents = page.get_contents()
    original = contents.get_data() if contents is not None else b""
    stream = DecodedStreamObject()
    stream.set_data(
        f"/{tag} <</MCID {mcid}>> BDC\n".encode("ascii")
        + original
        + b"\nEMC\n"
    )
    # Keep production PDFs compact after consolidating any original stream array.
    page[_name("Contents")] = writer._add_object(stream.flate_encode())


def add_accessible_tags(
    source_path: Path | str,
    destination_path: Path | str | None = None,
    *,
    title: str,
    page_titles: Sequence[str],
    language: str = "pt-BR",
) -> Path:
    """Create a structurally tagged copy of ``source_path``.

    ``destination_path`` may be the same file as ``source_path``.  In that case
    the tagged output is written atomically through a temporary sibling.
    """

    source = Path(source_path)
    destination = Path(destination_path) if destination_path else source
    reader = PdfReader(str(source))
    if len(page_titles) != len(reader.pages):
        raise ValueError(
            "A quantidade de títulos semânticos deve corresponder às páginas: "
            f"{len(page_titles)} títulos para {len(reader.pages)} páginas."
        )

    writer = PdfWriter()
    writer.clone_document_from_reader(reader)

    root = writer.root_object
    root[_name("Lang")] = TextStringObject(language)
    root[_name("MarkInfo")] = DictionaryObject(
        {
            _name("Marked"): BooleanObject(True),
            _name("Suspects"): BooleanObject(False),
        }
    )

    # Add the objects first so circular parent references are valid indirect refs.
    struct_root = DictionaryObject({_name("Type"): _name("StructTreeRoot")})
    struct_root_ref = writer._add_object(struct_root)
    document = DictionaryObject(
        {
            _name("Type"): _name("StructElem"),
            _name("S"): _name("Document"),
            _name("P"): struct_root_ref,
            _name("T"): TextStringObject(title),
            _name("Lang"): TextStringObject(language),
        }
    )
    document_ref = writer._add_object(document)

    page_section_refs = ArrayObject()
    parent_tree_numbers = ArrayObject()
    for index, (page, page_title) in enumerate(zip(writer.pages, page_titles)):
        _tag_page_content(writer, page)
        page[_name("StructParents")] = NumberObject(index)
        page[_name("Tabs")] = _name("S")

        section = DictionaryObject(
            {
                _name("Type"): _name("StructElem"),
                _name("S"): _name("Sect"),
                _name("P"): document_ref,
                _name("Pg"): page.indirect_reference,
                _name("K"): NumberObject(0),
                _name("T"): TextStringObject(page_title),
                _name("Lang"): TextStringObject(language),
            }
        )
        section_ref = writer._add_object(section)
        page_section_refs.append(section_ref)
        parent_tree_numbers.extend(
            (NumberObject(index), ArrayObject((section_ref,)))
        )

    document[_name("K")] = page_section_refs
    parent_tree = DictionaryObject({_name("Nums"): parent_tree_numbers})
    parent_tree_ref = writer._add_object(parent_tree)
    struct_root[_name("K")] = ArrayObject((document_ref,))
    struct_root[_name("ParentTree")] = parent_tree_ref
    struct_root[_name("ParentTreeNextKey")] = NumberObject(len(writer.pages))
    root[_name("StructTreeRoot")] = struct_root_ref

    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    output = destination
    if destination.resolve() == source.resolve():
        fd, temp_name = tempfile.mkstemp(
            prefix=f".{source.stem}-tagged-", suffix=".pdf", dir=source.parent
        )
        os.close(fd)
        temporary = Path(temp_name)
        output = temporary

    try:
        with output.open("wb") as pdf_file:
            writer.write(pdf_file)
        if temporary is not None:
            os.replace(temporary, destination)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()

    return destination
